# Generated by Django 5.0.1 on 2024-02-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0009_remove_round_game_remove_winninghand_round_and_more'),
        ('members', '0003_member_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_wind', models.TextField(choices=[('EAST', '東'), ('SOUTH', '南')], verbose_name='round wind')),
                ('round_number', models.IntegerField(verbose_name='round number')),
                ('tsumibo', models.IntegerField(verbose_name='tsumibo')),
                ('dead_wall', models.IntegerField(verbose_name='dead wall')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='HaiPai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(choices=[('EAST', '東'), ('SOUTH', '南'), ('WEST', '西'), ('NORTH', '北')], max_length=255, verbose_name='seats')),
                ('hai_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='hai pai')),
                ('syanten', models.IntegerField(blank=True, editable=False, null=True, verbose_name='syanten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.round')),
            ],
        ),
        migrations.CreateModel(
            name='WinningHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_type', models.CharField(choices=[('TSUMO', 'ツモ'), ('RON', 'ロン')], max_length=255, verbose_name='tsumo ron')),
                ('is_dealer', models.BooleanField(verbose_name='is dealer')),
                ('winning_hands', models.CharField(max_length=255, verbose_name='winning hands')),
                ('fuu', models.IntegerField(verbose_name='fuu')),
                ('faan', models.IntegerField(verbose_name='faan')),
                ('winning_score', models.IntegerField(editable=False, verbose_name='winning score')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.round')),
            ],
        ),
    ]
