# Generated by Django 5.0.1 on 2024-02-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_organization'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawnRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_hands', models.CharField(choices=[('TENPAI', '聴牌'), ('NOTEN', '不聴')], max_length=255, verbose_name='drawn hands')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.round')),
            ],
        ),
    ]
