# Generated by Django 5.0.1 on 2024-02-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_roundresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WinningHand',
        ),
    ]
