# Generated by Django 5.0.1 on 2024-01-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_kana', models.CharField(max_length=255)),
                ('official_x_id', models.CharField(max_length=255)),
                ('join_date', models.DateField(verbose_name='date joined league')),
            ],
        ),
    ]
