# Generated by Django 5.0.1 on 2024-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leave_date',
            field=models.DateField(null=True, verbose_name='date left league'),
        ),
    ]
