# Generated by Django 5.0.1 on 2024-01-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='date left league'),
        ),
    ]
