# Generated by Django 5.0.1 on 2024-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legular_start_date', models.DateField(blank=True, null=True, verbose_name='legular season start date')),
                ('legular_end_date', models.DateField(blank=True, null=True, verbose_name='legular season end date')),
                ('semifinal_start_date', models.DateField(blank=True, null=True, verbose_name='semifinal start date')),
                ('semifinal_end_date', models.DateField(blank=True, null=True, verbose_name='semifinal end date')),
                ('final_start_date', models.DateField(blank=True, null=True, verbose_name='final start date')),
                ('final_end_date', models.DateField(blank=True, null=True, verbose_name='final end date')),
            ],
        ),
    ]
