# Generated by Django 5.0.1 on 2024-02-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.TextField(choices=[('LEGULAR', 'legular'), ('SEMI_FINAL', 'semi_final'), ('FINAL', 'FINAL')], verbose_name='match type')),
                ('total_game_days', models.IntegerField(verbose_name='total game days')),
                ('game_date', models.DateField(verbose_name='date on game')),
                ('archive_url', models.URLField(verbose_name='archive url')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
    ]
