# Generated by Django 5.0.1 on 2024-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_days', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='match_type',
            field=models.TextField(choices=[('LEGULAR', 'legular'), ('SEMI_FINAL', 'semi final'), ('FINAL', 'final')], verbose_name='match type'),
        ),
    ]
