# Generated by Django 5.0.1 on 2024-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcaster',
            name='official_x_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
