# Generated by Django 5.0.1 on 2024-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='official_x_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='site_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
