# Generated by Django 5.0.1 on 2024-02-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_wind', models.TextField(choices=[('EAST', '東'), ('SOUTH', '南')], verbose_name='round wind')),
                ('round_number', models.IntegerField(verbose_name='round number')),
                ('tsumibo', models.IntegerField(verbose_name='tsumibo')),
                ('dead_wall', models.IntegerField(verbose_name='dead wall')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
