# Generated by Django 5.0.1 on 2024-02-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasters', '0002_broadcaster_official_x_id'),
        ('games', '0002_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBroadcaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_type', models.TextField(choices=[('CASTER', '実況'), ('COMMENTATOR', '解説'), ('PLAYER_COMMENTATOR', 'プレイヤー解説'), ('INTERVIEWER', 'インタビュー')], verbose_name='broadcaster type')),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcasters.broadcaster')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
