# Generated by Django 5.0.1 on 2024-02-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamebroadcaster'),
        ('members', '0003_member_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(choices=[(1, '1位'), (2, '2位'), (3, '3位'), (4, '4位'), (1.5, '同点1位'), (2.5, '同点2位'), (3.5, '同点3位'), (4.5, '同点4位')], verbose_name='position')),
                ('row_score', models.IntegerField(verbose_name='row score')),
                ('position_score', models.IntegerField(verbose_name='position score')),
                ('total_score', models.FloatField(verbose_name='total score')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
