# Generated by Django 5.0.1 on 2024-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='total_score',
            field=models.FloatField(editable=False, verbose_name='total score'),
        ),
    ]
