# Generated by Django 5.0.1 on 2024-02-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gameresult_total_score'),
        ('members', '0003_member_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaiPai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(choices=[('EAST', '東'), ('SOUTH', '南'), ('WEST', '西'), ('NORTH', '北')], max_length=255, verbose_name='seats')),
                ('hai_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='hai pai')),
                ('syanten', models.IntegerField(blank=True, editable=False, null=True, verbose_name='syanten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.round')),
            ],
        ),
    ]
