# Generated by Django 5.0.1 on 2024-02-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_winninghands'),
        ('members', '0003_member_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinningHands',
            new_name='WinningHand',
        ),
    ]
