# Generated by Django 5.0.1 on 2024-01-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_organization_delete_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
